### PR TITLE
Python 2 compatibility

### PR DESCRIPTION
**Pull request by nils-werner**
this PR entails necessary changes and tests for Python 2 compatibility:

 - `io.open()` instead of `open()`
 - conditionally using `unicode()` instead of `str()`
 - conditionally using `collections` instead of `collections.abc`
 - conditionally using `Queue` instead of `queue`
 - `unicode_literals` everywhere
 - `copy.copy()` instead of `list.copy()`
 - removed the handful of type annotations that were there
 - using `super(cls, self)` instead of `super()`
 - `tox` for cross-version testing
 - removed `doctr` dependency as it was unused

All tests pass on both Python versions.

### CODE REVIEW

**Comment by nils-werner** [comment]
But how would I do that in a Python 2 virtualenv?

**Comment by TomAugspurger** [comment]
Using the instructions [here](http://ipython.readthedocs.io/en/stable/install/kernel_install.html), from within your python2 virtualenvironment, you can

```python
python2 -m pip install ipykernel
python2 -m ipykernel install --user
```

There are additional arguments for controlling the name. With the default name of `python2.`

Stitching

    ```{python2}
    print "No parens!"
    ```
    
    ```{python3}
    print("With parens!")
    ```

gives


```html
<head>
</head>
<body>
<pre class="python2"><code>In [1]: print &quot;No parens!&quot;</code></pre>
<div class="output">
<pre><code>No parens!
</code></pre>
</div>
<pre class="python3"><code>In [1]: print(&quot;With parens!&quot;)</code></pre>
<div class="output">
<pre><code>With parens!
</code></pre>
</div>
</body>
</html>
```

**Comment by nils-werner** [comment]
But that requires me to have pystitch installed outside the virtualenv, no?

**Comment by TomAugspurger** [comment]
Correct, a python3 virtualenv with `stitch`, and a python2 virtualenv for your code / report.

**Comment by nils-werner** [comment]
Isn't that really complicated? I'd prefer having everything in one virtualenv.

**Comment by TomAugspurger** [comment]
I'd prefer not to have the extra compatibility code cluttering up the library :/

I'm also planning to implement code-chunk caching down the road, which I could see using python3-only syntax and features. Sorry, and I hope this didn't waste too much of your time.

**Pull request closed without merging**
